language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="caldav"
    - POST_INSTALL_HOOK="make"
    - PINS="webmachine:git+https://github.com/roburio/ocaml-webmachine.git#webdav"
  matrix:
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
notifications:
  email: false
